// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi3xN1bGzr6fdeaKE9O-9FmELK7Oo6RVY',
    appId: '1:1005834012811:web:d2daa98f0e8687a265ec8e',
    messagingSenderId: '1005834012811',
    projectId: 'buvyxjaa',
    authDomain: 'buvyxjaa.firebaseapp.com',
    storageBucket: 'buvyxjaa.firebasestorage.app',
    measurementId: 'G-MD6SVQH7MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDkA0YCZM70tnr9c9u1S-TvhQ0obTY7m4',
    appId: '1:1005834012811:android:4b1e3aeb88e6221365ec8e',
    messagingSenderId: '1005834012811',
    projectId: 'buvyxjaa',
    storageBucket: 'buvyxjaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7IN1ebxcSaOSbVwUc8qidPoia2rETCo',
    appId: '1:1005834012811:ios:763f30d8e96abf0965ec8e',
    messagingSenderId: '1005834012811',
    projectId: 'buvyxjaa',
    storageBucket: 'buvyxjaa.firebasestorage.app',
    iosBundleId: 'com.example.bubeacon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7IN1ebxcSaOSbVwUc8qidPoia2rETCo',
    appId: '1:1005834012811:ios:763f30d8e96abf0965ec8e',
    messagingSenderId: '1005834012811',
    projectId: 'buvyxjaa',
    storageBucket: 'buvyxjaa.firebasestorage.app',
    iosBundleId: 'com.example.bubeacon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi3xN1bGzr6fdeaKE9O-9FmELK7Oo6RVY',
    appId: '1:1005834012811:web:72dc8de17ff0f26565ec8e',
    messagingSenderId: '1005834012811',
    projectId: 'buvyxjaa',
    authDomain: 'buvyxjaa.firebaseapp.com',
    storageBucket: 'buvyxjaa.firebasestorage.app',
    measurementId: 'G-ED31BS7R7H',
  );

}