// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKAoixi8pDVhjj3Do6GiO6vfAWPCOgoyk',
    appId: '1:1042400144523:web:0e0ed78f55843cff6ff88e',
    messagingSenderId: '1042400144523',
    projectId: 'buvyx-project',
    authDomain: 'buvyx-project.firebaseapp.com',
    storageBucket: 'buvyx-project.firebasestorage.app',
    measurementId: 'G-GV8G8RQEY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiyyVrDT2y26d5v9fikwxVBXSqPvaFczs',
    appId: '1:1042400144523:android:856c64fb1ddeb7e76ff88e',
    messagingSenderId: '1042400144523',
    projectId: 'buvyx-project',
    storageBucket: 'buvyx-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA24WdZrE5PqUG8Ll01yIDu5ZsawixTUdI',
    appId: '1:1042400144523:ios:7acf9192021dcf006ff88e',
    messagingSenderId: '1042400144523',
    projectId: 'buvyx-project',
    storageBucket: 'buvyx-project.firebasestorage.app',
    iosBundleId: 'com.example.bubeacon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA24WdZrE5PqUG8Ll01yIDu5ZsawixTUdI',
    appId: '1:1042400144523:ios:7acf9192021dcf006ff88e',
    messagingSenderId: '1042400144523',
    projectId: 'buvyx-project',
    storageBucket: 'buvyx-project.firebasestorage.app',
    iosBundleId: 'com.example.bubeacon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKAoixi8pDVhjj3Do6GiO6vfAWPCOgoyk',
    appId: '1:1042400144523:web:311e5b3295405f136ff88e',
    messagingSenderId: '1042400144523',
    projectId: 'buvyx-project',
    authDomain: 'buvyx-project.firebaseapp.com',
    storageBucket: 'buvyx-project.firebasestorage.app',
    measurementId: 'G-1N5K0DPC9L',
  );
}
